manifest-version = 1

[component]
name = "google-bigquery"
version = "1.0.0"
icon-path = "icon.png"

category = "data-collection"
subcategory = "warehouse"
description = "Google bigquery component"
documentation = "https://github.com/edgee-cloud/bigquery-component"
repository = "https://github.com/edgee-cloud/bigquery-component"
language = "Rust"
wit-version = "1.0.1"

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && mv ./target/wasm32-wasip2/release/example_rust_component.wasm ./component.wasm"
output_path = "component.wasm"

# required only for auth
[component.settings.service_json]
type = "string"
title = "Service JSON"
secret = true

# required for the rest of the calls
[component.settings.dataset_id]
type = "string"
title = "Dataset ID"

[component.settings.project_id]
type = "string"
title = "Project ID"

[component.settings.table_id]
type = "string"
title = "Table ID"
